spring:
  #数据库相关
  datasource:
    name: mysql_datasource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性
#    url: jdbc:mysql://192.168.241.143:3306/yangningBPVlog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://123.57.53.196:3306/yangningBPVlog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Ckn20001103000.*
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true



  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #mybatis开启驼峰命名转换，不然实体类中驼峰命名的变量mybatis查出来都是null
  configuration:
    map-underscore-to-camel-case: true

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  page-size-zero: true